
default: helloworld.c
	gcc helloworld.c -o helloworld

dist: 
	tar -czf lab4a-504923307.tar.gz helloworld.c my_beaglebone.* connected.* copy.* build_run.* git.* Makefile README

clean:
	rm -f helloworld

