default: simpsh.c
	gcc -g -Wall -Wextra simpsh.c -o simpsh

clean:
	rm -f simpsh lab1-504923307.tar.gz

check:
	echo "tests / benchmarks located in simpsh_bm, simpsh_bash and simpsh_dash" \

dist:
	tar -cvzf lab1-504923307.tar.gz simpsh.c README Makefile lab1_report.pdf



